### 用户模块测试
GET http://localhost:8001/user-service/hello
Accept: application/json

### 网关测试测试接口
GET http://localhost:8000/user-service/hello
Accept: application/json

### 数量测试
GET http://localhost:8000/user-service/user/count
Accept: application/json

### 登录测试
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "phone": "189625217533333",
  "password": "123123"
}