### 用户模块测试
GET http://localhost:8001/user-service/hello
Accept: application/json

### 网关测试测试接口
GET http://localhost:8000/user-service/hello
Accept: application/json

### 数量测试
GET http://localhost:8000/user-service/user/count
Accept: application/json
token: {{token}}

### 登录测试
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "phone": "18962521753",
  "password": "123123"
}

> {%
 client.global.set("token", response.body.data.token)
 %}

### 注册测试
POST http://localhost:8000/user-service/user/register
Content-Type: application/json

{
  "phone": "18962526666",
  "password": "123123"
}

### 积分明细
GET http://localhost:8000/user-service/user/bonus?pageSize=1
Accept: application/json
token: {{token}}


### 签到
POST http://localhost:8000/user-service/user/check
Accept: application/json
token: {{token}}