server:
  port: 8001
#  servlet:
#    context-path: /user-service

#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Shanghai
#    serialization:
#      write-dates-as-timestamps: false
#  datasource:
#    url: jdbc:mysql://rm-cn-4xl3e1zjr00016fo.rwlb.rds.aliyuncs.com:3306/user_center?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: Jcx@@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: dev
#logging:
#  level:
#    top.flobby.share.user.mapper: debug

web:
  custom-file-upload: E:\java-projects\share-api\share-user\src\main\resources\file\


spring:
  servlet:
    multipart:
      # -1 表示无限大
      max-file-size: -1
      max-request-size: -1
  web:
    resources:
      # 默认有四个，重写配置后丢失默认路径
      static-locations: classpath:/static/,file:${web.custom-file-upload}

knife4j:
  enable: true
  setting:
    language: zh_cn
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      packages-to-scan: top.flobby.share.user
      paths-to-match: /**
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html
    tags-sorter: alpha