server:
  port: 8000

#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: route-user
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/**
#        - id: route-content
#          uri: lb://content-service
#          predicates:
#            - Path=/content-service/**
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            # 允许请求来源
#            allowedOriginPatterns: "*"
#            # 允许携带的头信息
#            allowedHeaders: "*"
#            # 允许请求方式
#            allowedMethods: "*"
#            # 是否允许携带 cookie
#            allowCredentials: "true"
#            # 跨域检测有效期，会发起一个 OPTION 请求
#            maxAge: "3600"
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: dev

knife4j:
  gateway:
    # 开区网关聚合文档 默认:/
    enabled: true
    # 服务发现
    discover:
      # 开启服务发现 默认:true
      enabled: true
      # 排除的服务名 默认:为空(建议排除网关服务)
      excluded-services: gateway-service
    routes:
      # 分组名称
      - name: user-server
        # 文档地址
        url: /user-service/v3/api-docs?group=default
        # context-path
        context-path: '/'
        # 服务名
        service-name: user-service
        # 排序
        order: 1
      - name: content-server
        # 文档地址
        url: /content-service/v3/api-docs?group=default
        # context-path
        context-path: '/'
        # 服务名
        service-name: content-service
        # 排序
        order: 2



