server:
  port: 8000

spring:
  application:
    name: share-gateway
  cloud:
    gateway:
      routes:
        - id: route-user
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/user-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许请求来源
            allowedOriginPatterns: "*"
            # 允许携带的头信息
            allowedHeaders: "*"
            # 允许请求方式
            allowedMethods: "*"
            # 是否允许携带 cookie
            allowCredentials: "true"
            # 跨域检测有效期，会发起一个 OPTION 请求
            maxAge: "3600"